import { chromium } from "playwright";
import { writeFileSync } from "node:fs";
const browser = await chromium.launch({ args: ["--no-sandbox", "--disable-dev-shm-usage"] });
const page = await browser.newPage({ viewport: { width: 1100, height: 720 } });
const errors = [];
page.on("pageerror", (e) => errors.push(String(e)));
await page.addInitScript(() => { try { localStorage.clear(); sessionStorage.clear(); } catch {} });
await page.goto("http://127.0.0.1:8080/", { waitUntil: "domcontentloaded", timeout: 15000 });
await page.waitForSelector("button", { timeout: 10000 });
await page.waitForTimeout(800);
await page.locator("button").filter({ hasText: /Land|Continue/ }).first().click({ force: true });
await new Promise((r) => setTimeout(r, 1800));
const hud = await page.evaluate(() => document.body.innerText, { timeout: 4000 });
await page.evaluate(() => document.querySelector('[aria-label="Agents"]')?.dispatchEvent(new MouseEvent("click", { bubbles: true })));
await new Promise((r) => setTimeout(r, 400));
const sheet = await page.evaluate(() => document.body.innerText, { timeout: 4000 });
const out = { errors, hud: hud.slice(0, 450), sheet: sheet.slice(0, 800) };
writeFileSync("/tmp/qa-soc.json", JSON.stringify(out, null, 2));
console.log(JSON.stringify(out, null, 2));
await browser.close();
